### ISSUE TITLE
PDF not accessible

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#18]
The PDF is still not accessible on the offline catalogue. For the latest version of the Data Loader, the metadata is _C46 Raspberry Pi.pdf_ but this is preceded by "C46" in the catalogue giving _C46/C46 Raspberry Pi.pdf_

Screenshots provided for the latest and the previous version of the Data Loader. Please note that the filename is different in the screenshot as I tried different permutations of filename with and without extension!

**Previous version:**
![TE screenshot  - PDF error 1](https://user-images.githubusercontent.com/35967074/113020837-e5a89380-917a-11eb-895c-dcd57e73f5d8.png)

**Current version:**
![TE screenshot  - PDF error 2](https://user-images.githubusercontent.com/35967074/113020881-f0fbbf00-917a-11eb-82e9-79131d5db111.png)

**Comment by marcolarosa** [comment]
Ooops - fixed in latest version

**Comment by rebekahhayes** [comment]
PDF is now accessible but the C46/ prefix is still showing. Is this an error or just how it is presented?
